language: objective-c
branches:
  only:
    master
before_install:
  - gem install activesupport -N -v 4.2.6
  - gem install slather --no-rdoc --no-ri --no-document --quiet
  - gem i cocoapods --no-ri --no-rdoc
  - pod install
script:
  - xctool test -workspace DeepLinkKit.xcworkspace -scheme ReceiverDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
  - slather
